### ISSUE TITLE
swipeLayout.close() does nothing

### ISSUE THREAD

**Issue by darzul** [daimajia/AndroidSwipeLayout#134]
Hi,

When I am calling the method ``close()`` in a ``SwipeListener()`` nothing happen.

Here is a sample code :

```
            mSwipeLayout.addDrag(SwipeLayout.DragEdge.Right, mHideSwipeView);
            mSwipeLayout.setClickToClose(true);
            mSwipeLayout.addSwipeListener(new SwipeLayout.SwipeListener() {
                @Override
                public void onStartOpen(SwipeLayout swipeLayout) {

                }

                @Override
                public void onOpen(SwipeLayout swipeLayout) {
                }

                @Override
                public void onStartClose(SwipeLayout swipeLayout) {

                }

                @Override
                public void onClose(SwipeLayout swipeLayout) {

                }

                @Override
                public void onUpdate(SwipeLayout swipeLayout, int leftOffset, int rightOffset) {

                }

                @Override
                public void onHandRelease(SwipeLayout swipeLayout, float xvel, float yvel) {
                    if(swipeLayout.getOpenStatus() == SwipeLayout.Status.Open) {
                        onPictureHide();
                        swipeLayout.close();
                    }
                }
            });
```
This code is in a ``ViewHolder`` which is in ``Adapter`` which extend ``RecyclerSwipeAdapter``

The goal is to trig an action once the swipe is visible and totally open. Then it closes itself automatically.

Unfortunatly  the bottom view does not close... With a ``swipeLayout.close(false);`` it works but there is the issue #125 ! Finally with a call on adapter.closeItem(position) it works, but there is a ``mRecyclerAdapter.notifyDataSetChanged();`` which destroy my UX.

Feel free to ask more information ! :)

**Comment by linfaxin** [comment]
Try close with a delay:

    swipeLayout.postDelay(new Runnable() {
        @Override
        public void run() {
            swipeLayout.close();
        }
    }, 50);

**Comment by darzul** [comment]
It works fine :) thank you

Just a little edit on the method name which is ``postDelayed()``

I will let the issue open because this solution is a kind of hack, but very good for the moment !

**Comment by daimajia** [comment]
@darzul  Awesome!
Thanks @linfaxin 's help.

**Comment by matpatten** [comment]
close(true,false) closes correctly but still calls onClose

**Comment by jpshelley** [comment]
I don't believe you @matpatten..Joking! The issue is with the smooth+notify with the close method.

if smooth:
https://github.com/daimajia/AndroidSwipeLayout/blob/f9ac392ef6cd2588cd78458ab2c972e696e1a7dc/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L1321

then our dragHelper will issue this method:
https://github.com/daimajia/AndroidSwipeLayout/blob/f9ac392ef6cd2588cd78458ab2c972e696e1a7dc/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L385

And the dispatch does issue a notify regardless.

Correct me if I'm wrong @daimajia. Otherwise feel free to send a pull request.

**Comment by jpshelley** [comment]
And @darzul in any adapter try to make use of the ItemManager class:
mItemManger.closeItem(int pos)
Since you're RecyclerViewAdapter should be extended from RecyclerSwipeAdapter that should be inherited.

**Comment by daimajia** [comment]
@matpatten Make sure that you are using the latest version. It shouldn't call the onClose listener, if you make sure that you are all right, please paste your code here.

**Comment by jpshelley** [comment]
@daimajia See my comment. I think there may be a bug. I'll try to replicate it tomorrow. (My Test Suite I'm building should help with things like this as well.)

**Comment by daimajia** [comment]
@jpshelley Yeah, I got your point! the dispatch method should handle the notify flag. 
Looking forward your test suite, it will make this library much more professional. ^^

**Comment by DVassilev** [comment]
@daimajia close(true, false) and open(true, false) still call onClose and onOpen. I do not think it is fixed, could you please take a look at it agian?

**Comment by rbakhshi** [comment]
When using the SwipeLayout in recycler view, `close(false)` method does not really work and `close()` ends up in an inconsistent state when view is recycled ( sometimes remains half open or in best case, use can see the swipe is being closed on recycled views)

To your point @jpshelley on using `RecyclerSwipAdapter` that also fails because the `closeItem` method eventually calls `notifyDataSetChanged` which if you call it in your `onBindViewHolder` it endsup in and error from RecyclerView that `notifyDataSetChanged` is not allowed at that time.

Anyone has any idea how to deal with this?
