### ISSUE TITLE
remove an listview item in swipeadater?

### ISSUE THREAD

**Issue by huchunyu** [daimajia/AndroidSwipeLayout#17]
I have a horizontal list view and for each item  I want to delete it with swipe gesture. I put the delete logic in onOpen method, but seems it's not working. 

``` java
@Override
            public void onOpen(SwipeLayout layout) {
                 //when the BottomView totally show.
                Log.d("Position", Integer.toString(position));

                mPictures.remove(position);
                notifyDataSetChanged();

            }
```

**Comment by af6767** [comment]
Because i ran into same issues, my question, what is the answer to this ?
if a item is removed from adapter, for every item the onOpen Method in SwipeListener is fired.

**Comment by m2kk** [comment]
Hey guys,

so there's definitely some problem with this:
Target: get swipe2delete working
first: if you add swipelisteners you definitly got multiple of them… and on swiping you delete  multiple items
second: there is not method: removeAllSwipeListener (even searched the github project, does not exist)
third: even on making one instance of swipelistener, remove and add it oneByOne to every view, so that there should be just "this one listener" at each view, after scrolling a bit, you got multiple onOpen calls at an item.
fourth: for instance there are 40 items, deleting one by one beginning at top works, but if you like scroll a bit down, up, swipe2delete some items and continue, i bet, within 30 seconds doing this, you definitly get one time, that the bottomView stays opened for the next item.

I used the code given in a sample (demo folder):
            mItemManger.removeShownLayouts(layout);
            data.remove(dataItem);
            int itemPosition = getItemIndex(dataItem);
            notifyItemRemoved(itemPosition);
            notifyItemRangeChanged(itemPosition, data.size());
            mItemManger.closeAllItems();

fifth: so sorry, for now I didn't get it to work constantly. at least on 15 deletions, one makes some broken state :(
any advice would be perfect.

**Comment by basith0304** [comment]
When I’m using Kitkat Version . If i swipe the list item, delete & open button appeared and suddenly its closed .other versions its working good .

Please help me

**Comment by Michal-easycore** [comment]
Hey,
don't know guys if you are still facing this issue, but right now I am having exact same problem using lib version 1.2.0. I resolved the problem simulating removeAllSwipeListeners() by having my own List.

    public class FixedSwipeLayout extends SwipeLayout {

    private List<SwipeListener> swipeListeners;

    public FixedSwipeLayout(Context context) {
        super(context);
        swipeListeners = new ArrayList<>();
    }

    public FixedSwipeLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
        swipeListeners = new ArrayList<>();
    }

    public FixedSwipeLayout(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        swipeListeners = new ArrayList<>();
    }

    @Override
    public void addSwipeListener(SwipeListener listener) {
        for (SwipeListener l : swipeListeners) {
            removeSwipeListener(l);
        }
        swipeListeners.clear();

        swipeListeners.add(listener);
        super.addSwipeListener(listener);
    }
}

I think correctly solving this problem is to have Set instead of List inside SwipeLayout. I hope it will be fixed soon.
